# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Artist.create(name: 'Micheal Jackson')
Artist.create(name: 'Eminem')
Artist.create(name: 'Justin Bieber')
Artist.create(name: 'Adele')
Artist.create(name: 'Selena Gomez')

Album.create(artist_id: 1, title: 'Thriller', year: 1982, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png')
Album.create(artist_id: 1, title: 'Bad', year: 1987, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Michael_Jackson_-_Bad.png/220px-Michael_Jackson_-_Bad.png')
Album.create(artist_id: 2, title: 'The Eminem Show', year: 2002, genre: 'rap', image: 'https://images-na.ssl-images-amazon.com/images/I/61jxguiMreL._SL1200_.jpg')
Album.create(artist_id: 2, title: 'Encore', year: 2004, genre: 'rap', image: 'https://e.snmc.io/i/600/w/0f17fa189f48485d75370965044c3dee/1311548')
Album.create(artist_id: 3, title: 'My World 2.0', year: 2010, genre: 'pop', image: 'https://i.ytimg.com/vi/Iza2d8eSJRQ/hqdefault.jpg')
Album.create(artist_id: 3, title: 'Believe', year: 2012, genre: 'pop', image: 'https://images-na.ssl-images-amazon.com/images/I/71GkWgyS8YL._SL1400_.jpg')
Album.create(artist_id: 4, title: "19", year: 2008, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/f/f8/Adele_-_19.png')
Album.create(artist_id: 4, title: "21", year: 2011, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Adele_-_21.png')
Album.create(artist_id: 4, title: "25", year: 2015, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/9/96/Adele_-_25_%28Official_Album_Cover%29.png')
Album.create(artist_id: 5, title: "Stars Dance", year: 2013, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/f/f1/Stars_Dance.png')
Album.create(artist_id: 5, title: "Revival", year: 2015, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/4/42/Selena_Gomez_-_Revival_%28Official_Deluxe_Cover%29.png')
Album.create(artist_id: 5, title: "Rare", year: 2020, genre: 'pop', image: 'https://upload.wikimedia.org/wikipedia/en/d/d1/Selena_Gomez_-_Rare.png')

Song.create(album_id: 1, name: "Wanna Be Startin' Somethin'")
Song.create(album_id: 1, name: "Baby Be Mine")
Song.create(album_id: 1, name: "The Girl Is Mine")
Song.create(album_id: 1, name: "Thriller")
Song.create(album_id: 1, name: "Beat It")
Song.create(album_id: 1, name: "Billie Jean")
Song.create(album_id: 1, name: "Human Nature")
Song.create(album_id: 1, name: "P.Y.T. (Pretty Young Thing)")
Song.create(album_id: 1, name: "The Lady in My Life")

Song.create(album_id: 2, name: "Bad")
Song.create(album_id: 2, name: "The Way You Make Me Feel")
Song.create(album_id: 2, name: "Speed Demon")
Song.create(album_id: 2, name: "Liberian Girl")
Song.create(album_id: 2, name: "Just Good Friends")
Song.create(album_id: 2, name: "Another Part of Me")
Song.create(album_id: 2, name: "Man in the Mirror")
Song.create(album_id: 2, name: "I Just Can't Stop Loving You")
Song.create(album_id: 2, name: "Dirty Diana")
Song.create(album_id: 2, name: "Smooth Criminal")
Song.create(album_id: 2, name: "Leave Me Alone")

Song.create(album_id: 3, name: "Curtains Up (skit)")
Song.create(album_id: 3, name: "White America")
Song.create(album_id: 3, name: "Business")
Song.create(album_id: 3, name: "Cleanin' Out My Closet")
Song.create(album_id: 3, name: "Square Dance")
Song.create(album_id: 3, name: "The Kiss (skit)")
Song.create(album_id: 3, name: "Soldier")
Song.create(album_id: 3, name: "Say Goodbye Hollywood")
Song.create(album_id: 3, name: "Drips")
Song.create(album_id: 3, name: "Without Me")
Song.create(album_id: 3, name: "Paul Rosenberg (skit)")
Song.create(album_id: 3, name: "Sing for the Moment")
Song.create(album_id: 3, name: "Superman")
Song.create(album_id: 3, name: "Hailie's Song")
Song.create(album_id: 3, name: "Steve Berman (skit)")
Song.create(album_id: 3, name: "When the Music Stops")
Song.create(album_id: 3, name: "Say What You Say")
Song.create(album_id: 3, name: "'Till I Collapse")
Song.create(album_id: 3, name: "My Dad's Gone Crazy")
Song.create(album_id: 3, name: "Curtains Close (skit)")

Song.create(album_id: 4, name: "Curtains Up (skit)")
Song.create(album_id: 4, name: "Evil Deeds")
Song.create(album_id: 4, name: "Never Enough")
Song.create(album_id: 4, name: "Yellow Brick Road")
Song.create(album_id: 4, name: "Like Tou Soldiers")
Song.create(album_id: 4, name: "Mosh")
Song.create(album_id: 4, name: "Puke")
Song.create(album_id: 4, name: "My 1st Single")
Song.create(album_id: 4, name: "Paul (skit)")
Song.create(album_id: 4, name: "Rain Man")
Song.create(album_id: 4, name: "Big Weenie")
Song.create(album_id: 4, name: "Em Calls Paul (skit)")
Song.create(album_id: 4, name: "Just Lose It")
Song.create(album_id: 4, name: "Ass Like That")
Song.create(album_id: 4, name: "Spend Some Time")
Song.create(album_id: 4, name: "Mockingbird")
Song.create(album_id: 4, name: "Crazy in Love")
Song.create(album_id: 4, name: "One Shot 2 Shot")
Song.create(album_id: 4, name: "Final Thought(skit)")
Song.create(album_id: 4, name: "Encore(Curtains)")

Song.create(album_id: 5, name: "Baby")
Song.create(album_id: 5, name: "Somebody to Love")
Song.create(album_id: 5, name: "Stuck in the Moment")
Song.create(album_id: 5, name: "U Smile")
Song.create(album_id: 5, name: "Runaway Love")
Song.create(album_id: 5, name: "Never Let You GO")
Song.create(album_id: 5, name: "Overboard")
Song.create(album_id: 5, name: "Eenie Meenie")
Song.create(album_id: 5, name: "Up")
Song.create(album_id: 5, name: "That Should Be Me")


Song.create(album_id: 6, name: "All Around the World")
Song.create(album_id: 6, name: "Boyfriend")
Song.create(album_id: 6, name: "As Long as You Love Me")
Song.create(album_id: 6, name: "Catching Feelings")
Song.create(album_id: 6, name: "Take You")
Song.create(album_id: 6, name: "Right Here")
Song.create(album_id: 6, name: "Fall")
Song.create(album_id: 6, name: "Die in Your Arms")
Song.create(album_id: 6, name: "Thought of You")
Song.create(album_id: 6, name: "Beauty and a Beat")
Song.create(album_id: 6, name: "One Love")
Song.create(album_id: 6, name: "Be Alright")
Song.create(album_id: 6, name: "Believe")

Song.create(album_id: 7, name: "Daydreamer")
Song.create(album_id: 7, name: "Best for Last")
Song.create(album_id: 7, name: "Chasing Pavements")
Song.create(album_id: 7, name: "Cold Shoulder")
Song.create(album_id: 7, name: "Crazy for You")
Song.create(album_id: 7, name: "Melt My Heart to Stone")
Song.create(album_id: 7, name: "First Love")
Song.create(album_id: 7, name: "Right as Rain")
Song.create(album_id: 7, name: "Make You Feel My Love")
Song.create(album_id: 7, name: "My Same")
Song.create(album_id: 7, name: "Tired")
Song.create(album_id: 7, name: "Hometown Glory")

Song.create(album_id: 8, name: "Rolling in the Deep")
Song.create(album_id: 8, name: "Rumour Has It")
Song.create(album_id: 8, name: "Turning Tables")
Song.create(album_id: 8, name: "Don't You Remember")
Song.create(album_id: 8, name: "Set Fire to the Rain")
Song.create(album_id: 8, name: "He Won't Go")
Song.create(album_id: 8, name: "Take It All")
Song.create(album_id: 8, name: "I'll Be Waiting")
Song.create(album_id: 8, name: "One and Only")
Song.create(album_id: 8, name: "Lovesong")
Song.create(album_id: 8, name: "Someone like You")

Song.create(album_id: 9, name: "Hello")
Song.create(album_id: 9, name: "Send My Love (To Your New Lover)")
Song.create(album_id: 9, name: "I Miss You")
Song.create(album_id: 9, name: "When We Were Young")
Song.create(album_id: 9, name: "Remedy")
Song.create(album_id: 9, name: "Water Under the Bridge")
Song.create(album_id: 9, name: "River Lea")
Song.create(album_id: 9, name: "Love in the Dark")
Song.create(album_id: 9, name: "Million Years Ago")
Song.create(album_id: 9, name: "All I Ask")
Song.create(album_id: 9, name: "Sweetest Devotion")

Song.create(album_id: 10, name: "Birthday")
Song.create(album_id: 10, name: "Slow Down")
Song.create(album_id: 10, name: "Stars Dance")
Song.create(album_id: 10, name: "Like a Champion")
Song.create(album_id: 10, name: "Come & Get It")
Song.create(album_id: 10, name: "Forget Forever")
Song.create(album_id: 10, name: "Save the Day")
Song.create(album_id: 10, name: "B.E.A.T.")
Song.create(album_id: 10, name: "Write Your Name")
Song.create(album_id: 10, name: "Undercover")
Song.create(album_id: 10, name: "Love Will Remember")

Song.create(album_id: 11, name: "Revival")
Song.create(album_id: 11, name: "Kill Em with Kindness")
Song.create(album_id: 11, name: "Hands to Myself")
Song.create(album_id: 11, name: "Same Old Love")
Song.create(album_id: 11, name: "Sober")
Song.create(album_id: 11, name: "Good for You")
Song.create(album_id: 11, name: "Camouflage")
Song.create(album_id: 11, name: "Me & the Rhythm")
Song.create(album_id: 11, name: "Survivors")
Song.create(album_id: 11, name: "Body Heat")
Song.create(album_id: 11, name: "Rise")

Song.create(album_id: 12, name: "Rare")
Song.create(album_id: 12, name: "Dance Again")
Song.create(album_id: 12, name: "Look at Her Now")
Song.create(album_id: 12, name: "Lose You to Love Me")
Song.create(album_id: 12, name: "Ring")
Song.create(album_id: 12, name: "Vulnerable")
Song.create(album_id: 12, name: "People You Know")
Song.create(album_id: 12, name: "Let Me Get Me")
Song.create(album_id: 12, name: "Crowded Room")
Song.create(album_id: 12, name: "Kinda Crazy")
Song.create(album_id: 12, name: "Fun")
Song.create(album_id: 12, name: "Cut You Off")
Song.create(album_id: 12, name: "A Sweeter Place")


